### ISSUE TITLE
Insert Callout

### ISSUE THREAD

**Issue by rokville** [eth-p/obsidian-callout-manager#2]
Feature Request:
Add the ability to see callout options, select one (mouse or keyboard), and insert it at the cursor.

Use Case/Example:
- Place cursor
- Hotkey (or invoke Command Pallet, and choose Insert Callout)
- Modal pops up with your callouts in a list (maybe a smaller version (less screen real estate) of the management screen.  
- Arrow down to the desired callout, 
- Hit enter

(possibly other options - like make collapsible - but it's so easy to add that after. maybe have a setting for a default colapse state?... so you can invoke the modal, select your callout can get back to your doc as quickly as possible.

I love the call out management in this, but I feel it would be a complete callout toolkit if you could quickly see your options, pick one, and insert it (similar to the Admonition plugin, but I think the insert modal is a little over-complicated).

**Comment by eth-p** [comment]
Great suggestion!

At the moment I've been using a [modified version](https://github.com/tth05/obsidian-completr/pull/54) of the Completr plugin for inserting callouts, but I'll get to work on adding a command that opens a modal to insert a callout.

In the case where you have text selected, what do you think should happen? I feel like what would be expected is that it wraps the text in a callout block and moves the cursor to the end, like this:

```md
Some highlighted text.
```

Into 

```md
> [!warning]
> Some highlighted text.|
```

**Comment by rokville** [comment]
Awesome, Thank you!.  I completely agree with your example.

**Comment by kickTiger** [comment]
Would you consider the following operation:
1. After selecting the text, call the command through a shortcut key to insert the command.
2. Popup a window like in the Admonition plugin, where one can select the callout style and whether to collapse it.
3. Finally, the selected text will be modified to add a callout style.
![image](https://user-images.githubusercontent.com/3623068/227704440-bd0d7105-461a-41ed-8083-f653dcfd7f07.png)

I have been using the Admonition plugin to insert callout syntax, which is very convenient. However, I have found that the Admonition plugin cannot recognize callouts that are customized by the callout-manager.

**Comment by eth-p** [comment]
Looks like a good approach, but I'd have a little bit of prerequisite work to do.

If the "callout type" field is going to be a text-searchable dropdown instead of a list, I would want to first split off and clean up the code I'm currently using to search through callouts inside the Manage Callouts pane. That would allow the behaviour to remain consistent between the new dropdown and the existing search field.

**Comment by eth-p** [comment]
I just realized something:

Another possibility might to be to make a pull request to add [Callout Manager API](https://github.com/eth-p/obsidian-callout-manager/tree/master/api) support to the Admonition plugin. That's actually the intended use case for this plugin's API to begin with 😄

**Comment by rokville** [comment]
I can understand the approach of adding API support for Admonition, but Ideally, **one or the other** would be useful and you wouldn't need both for such standard use cases.  I used Admonition before, but I feel yours is very clean and it simplifies things down to "here are your callouts and you can see and modify them as you wish" it'd be cool if it also had a simple insert that let you preview the main insert options (name/icon/color).  Also, The Compltr version (working with your API) doesn't show customized icons/colors so it's not ideal.  

I have no idea what is involved with adding the features we are talking about, so maybe the API route is simpler, but it without an insert option, another accompanying plugin will be required to make use of a very core utility of Callouts (picking and inserting one).

In a somewhat related matter, the **Style Settings** plugin seems like it might be something to consider with how your plugin works in obsidian.  Right now, if I want to dig into callouts, I need to consider checking Style Settings (my theme, AnuPpiccin has some callout modification options there).  Just an fyi, if you hadn't thought about it.

Thanks again for your work!

**Comment by eth-p** [comment]
> Ideally, one or the other would be useful and you wouldn't need both for such standard use cases. [...] Without an insert option, another accompanying plugin will be required to make use of a very core utility of Callouts (picking and inserting one).

Good point on that. With inserting callouts being such a fundamental feature, it's probably best that it's implemented directly in Callout Manager.

> Also, The Compltr version (working with your API) doesn't show customized icons/colors so it's not ideal.

Er... that shouldn't happen. It's supposed to update whenever a callout is changed. It might be related to a load order bug that I fixed for the upcoming 1.1 release, but I'll need to do some more investigating to be sure.

> I have no idea what is involved with adding the features we are talking about, so maybe the API route is simpler.

With what I've been working on today, I'm actually about 70% of the way there already. It should be pretty straightforward once I'm done refactoring the code to search through callouts.

> In a somewhat related matter, the Style Settings plugin seems like it might be something to consider with how your plugin works in obsidian.

As in, giving the ability to customize additional per-callout settings? If that's what you mean, I'm already planning on adding a field for custom CSS :)

Or if you meant something like giving theme authors the ability to create their own user-configurable settings per callout, that was feature I was considering adding at some point.

**Comment by rokville** [comment]
I really appreciate your openness.  I think you have a great vision for this plugin/api.  I think I was just mentioning the Style Settings thing because call out color/icon/etc seems to be related to "style" - I don't know if your plugin needs to talk to style settings at all, but I thought I mention it just so you could consider it if you hadn't yet.  Nothing critical.  
Great work on all this!

**Comment by brimwats** [comment]
Secondng that "with inserting callouts being such a fundamental feature, it's probably best that it's implemented directly in Callout Manager"; came here to suggest this feature! you could put a button to the right of the edit button in the modal

**Comment by eth-p** [comment]
Just to keep everyone updated: I've been a bit busy recently with finals and other Obsidian-related projects (that will directly benefit this plugin), but this is still on the roadmap for the next release. If all goes well, I'll have the chance to resume work on this later in the month!

**Comment by AMGMNPLK** [comment]
Another suggestion is adding a command to each type of callout, so we can even skip the interface for the most common callouts.

The plugin is great, thank you @eth-p !!

**Comment by Enteleform** [comment]
The [personal-assistant](https://github.com/edonyzpc/personal-assistant/tree/master) plugin has a pretty good implementation of this.  Definitely useful how it shows previews of the callouts.

![personal-assistant](https://github.com/eth-p/obsidian-callout-manager/assets/10906415/01e514cd-4205-4b4b-be33-aa9f7529220c)

**Comment by creativefibro** [comment]
I was just wondering if this plugin is still supported. I came to look for this feature and saw a request and realised it hadn't been updated in a year.
I just went into my my Callout Manager to find the one I wanted to use and realised that recently a lot have been added. It would be useful to know which theme/plugin added them and if there could be a way to select any sets to potentially switch off. This is my current list.
![CleanShot 2024-02-05 at 6  04 49@2x](https://github.com/eth-p/obsidian-callout-manager/assets/39191327/7be88d33-c4f9-4c0b-8051-d412a9d179f9)

**Comment by eth-p** [comment]
Sorry for the lack of communication around things. I haven't abandoned this plugin, it's just been a while since I've had the chance to work on it.

I started the plugin at the start of my final year at university to help with note taking and ended up not having enough time to maintain or update it. I'm graduating in a couple of months, though. Getting everything fixed is high on my backlog, so it shouldn't be too much of a wait longer :)

**Comment by decheine** [comment]
Hi @eth-p, I went ahead and implemented a few features in my fork of this repository, https://github.com/decheine/obsidian-callout-manager
I added a Ribbon button that takes you straight to Manage Callouts, and added an "Insert" button next to each one that inserts the callout at the cursor location. 

I also added a dropdown menu with default colors for callout colors. 

If you don't have any objections I'll go ahead with a pull request.

**Comment by decheine** [comment]
Here is a preview of the insert capability. I don't know if this is exactly what people would want but I think it works well enough.

![InserCallout](https://github.com/eth-p/obsidian-callout-manager/assets/44585814/e6de8611-7c0f-4f45-a7a7-1fb152663b60)

**Comment by eth-p** [comment]
Hi @decheine, that looks great!

I would be happy to merge it when you make a PR.
