### ISSUE TITLE
"Note" default Obsidian callout not found in the plugin's callout list (Windows / Linux)

### ISSUE THREAD

**Issue by DanyGee** [eth-p/obsidian-callout-manager#5]
Plugin does not list the "Note" callout in the Obsidian default callouts list:
![image](https://github.com/eth-p/obsidian-callout-manager/assets/26818551/395805bd-e4f9-436e-a7f3-2294e6e4244b)
(Obsidian default Note callout)

![image](https://github.com/eth-p/obsidian-callout-manager/assets/26818551/035810b5-68c2-4530-a9b2-1b802acd4e2c)
(message from the plugin)

![image](https://github.com/eth-p/obsidian-callout-manager/assets/26818551/ffba9ee1-59e7-404b-8ba4-2e2c3b654059)
(plugin callout list)

👀 Observed on both Windows11 and Linux (Manjaro).
📦 Obsidian version 1.2.8.

**Comment by RaviOnline** [comment]
The default `Question` callout is missing as well. Submitting a PR to fix this.
